"""make day_list date nullable for standalone lists

Revision ID: 19af8110dce3
Revises: c98274845125
Create Date: 2026-09-13 17:42:53.226447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19af8110dce3'
down_revision: Union[str, Sequence[str], None] = 'c98274845125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('day_lists', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('day_lists', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
