"""add task trash fields and file task_id set null on delete

Revision ID: 9dad73a98018
Revises: 68c93b4a8fc4
Create Date: 2026-09-13 15:24:01.274399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dad73a98018'
down_revision: Union[str, Sequence[str], None] = '68c93b4a8fc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_task_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('is_trashed', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'trashed_at')
    op.drop_column('tasks', 'is_trashed')
    op.drop_constraint('files_task_id_fkey', 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_task_id_fkey'), 'files', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
