"""create day_lists and day_list_items tables

Revision ID: c98274845125
Revises: 9dad73a98018
Create Date: 2026-09-13 17:25:34.868585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98274845125'
down_revision: Union[str, Sequence[str], None] = '9dad73a98018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_lists_date'), 'day_lists', ['date'], unique=False)
    op.create_index(op.f('ix_day_lists_user_id'), 'day_lists', ['user_id'], unique=False)
    op.create_table('day_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_done', sa.Boolean(), nullable=False),
    sa.Column('day_list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['day_list_id'], ['day_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_list_items_day_list_id'), 'day_list_items', ['day_list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_day_list_items_day_list_id'), table_name='day_list_items')
    op.drop_table('day_list_items')
    op.drop_index(op.f('ix_day_lists_user_id'), table_name='day_lists')
    op.drop_index(op.f('ix_day_lists_date'), table_name='day_lists')
    op.drop_table('day_lists')
    # ### end Alembic commands ###
